AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  apigateway:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: apigateway/index.handler
      Runtime: nodejs6.10
      AutoPublishAlias: newdeploy
      Description: ''
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          tier: AQICAHjAmbuG+u1S43eFDKTmzlVvigBfWugX9syzfdLGquWiAwEUTcRFWrs1xRbinZmCi/9OAAAAaDBmBgkqhkiG9w0BBwagWTBXAgEAMFIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMibioT/xEZKTTKWk0AgEQgCXL2uLhpIpzsCqeWBF3tc8yL+H59socSjaBzMAskioY0N9mWGsn
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: /
            Method: GET
      KmsKeyArn: 
        'Fn::Sub': 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/mylambdaKMS'
  apigatewayPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - apigateway
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'
